<a href="https://colab.research.google.com/github/wenshanliu653/Udemy_Tensorflow_ML/blob/main/00_tensorflow_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **In this notebook, we're going to cover some of the most fundamental concepts of tensors using TensorFlow**
More specifically, we're going to cover:

Introduction to tensors

Getting information from tensors

Manipulating tensors

Tensors & NumPy

Using @tf.function (a way to speed up your regular Python functions)

Using GPUs with TensorFlow (or TPUs)

Exercises to try for yourself!

**Introduction to Tensors**

In [2]:
#import tensorflow
import tensorflow as tf
print(tf.__version__)


2.15.0


# **#Create the tensors with tf.constant()**

In [4]:

scalar = tf.constant(7) #常數張量7
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
scalar.ndim #dimention

0

In [6]:
#Create a vector

vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
vector.ndim

1

In [8]:
#Create a matrix (多維度)

matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
matrix.ndim

2

In [22]:

# Create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16) # specify the data type with dtype parameter

another_matrix


<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [23]:
another_matrix.ndim  #why is 2???  --因為shape() 內 只有兩個維度

2

In [25]:

# Let's create a tensor
tensor = tf.constant([[[1, 2, 3,],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor


<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [27]:
tensor.ndim #維度 shape()3

3

What we've created so far:

Scalar: a single number

Vector: a number with direction (e.g. wind speed and direction)

Matrix: a 2-dimensional array of numbers

Tensor: an n-dimensional array of numbers (when n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)


# **Creating tensors with tf.Variable()**

In [36]:
#create the same tensor with tf.Variable() as bove

changeable_tensor = tf.Variable([10,7]) #可改變的張量
unchangeable_tensor = tf.constant([10,7]) #不可改變的張量

changeable_tensor, unchangeable_tensor  #印出來基本一樣

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [31]:
# Let's try change one of the elements in our changeable tensor
changeable_tensor[0] = 7 #不可改第一個element, 會報錯
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [33]:
# How about we try .assign()
changeable_tensor[0].assign(7) #將第一element assign 7 ,可執行
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [40]:
# Let's try change one of the elements in our changeable tensor
unchangeable_tensor[0] = 7 #不可用，因為constant()方式 不支援
unchangeable_tensor

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [42]:
unchangeable_tensor[0].assign(7)  #不可用，因為constant()方式 不支援
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

 Note: Rarely in practice will you need to decide whether to use `tf.constant` or `tf.Variable` to create tensors, as TensorFlow does this for you. However, if in doubt, use `tf.constant` and change it later if needed.

***總結：Constant() 和Variable() 處理tensor ***
- Constant() 不支援直接改element
- Constant() 不支援assign() 賦值

-->EagerTensor()問題

- Variable() 不支援直接改element
- Variable() 支援assign() 賦值


# **Creating random tensors**
Random tensors are tensors of some arbitrary size which contain random numbers.

In [44]:
#Create 2 random (but not same) tensors
# random.Genertor --> 常態分佈
random_1 = tf.random.Generator.from_seed(42)  #如果兩個seed數值一樣，randomn 出來也會一樣
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

random_1, random_2 ,random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

# **Shuffle the order of elements in a tensor 打亂順序**


In [46]:
# Shuffle a tesnor (valuable for when you want to shuffle your data so the inherent order doesn't effect learning)
#打亂data 順序 可能是希望機器交叉學習不同類型data 而不是按照順順序學習data
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
# Shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

In [48]:
# Shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled, seed=42)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [50]:
tf.random.shuffle(not_shuffled, seed=42)  #每次執行可能都不一樣順序


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [55]:
#但如果設定seed 為固定值，執行順序就不會變了
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [66]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [70]:

tf.random.set_seed(42) # global level random seed
tf.random.shuffle(not_shuffled, seed=42) # operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

# **Other ways to make tensors**

In [71]:
# Create a tensor of all ones
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [72]:

# Create a tensor of all ones
tf.zeros((3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

# **Turn NumPy arrays into tensors**
The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU (much faster for numerical computing).


In [75]:
#Turn Numpy array into tensors
import numpy as np
numpy_A = np.arange(1,25, dtype=np.int32) # create a NumPy array between 1 and 25
numpy_A

# X = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [81]:
A = tf.constant(numpy_A, shape=(3,8)) #2維的 shape 數值相乘 ＝原先的element numbers
B = tf.constant(numpy_A) #原先1維
C = tf.constant(numpy_A, shape=(2,3,4)) #3維的 shape 數值相乘 ＝原先的element numbers

A, B, C


(<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>)

In [82]:
A.ndim, B.ndim, C.ndim #分別是２維 １維 ３維

(2, 1, 3)